#!/bin/bash

# we need gettext (is loaded in ssft.sh or cloned...)
if [ -f /usr/bin/gettext.sh ]; then
	. /usr/bin/gettext.sh || exit 1
else
	exit 1
fi
#---------------------------------------------------------------------
# we need root rights
#---------------------------------------------------------------------
if [ "$(id -u)" -ne 0 ]; then
	[ -x "$(which su-to-root)" ] && exec su-to-root -X -c "$0" "$@"
	printf "ERROR: $0 needs root capabilities, please start it as root\n\n" >&2
	exit 1
fi

TEXTDOMAIN="gprsconnect"
export TEXTDOMAIN
TEXTDOMAINDIR=/usr/share/locale
export TEXTDOMAINDIR


SSFTSH="$(which ssft.sh)"			|| SSFTSH="/usr/bin/ssft.sh"
# initialize ssft
. "$SSFTSH"
[ -n "$SSFT_FRONTEND" ] ||  SSFT_FRONTEND="$(ssft_choose_frontend)"


bailout()
{
	exit 0
}

trap bailout 1 2 3 15


disconnect()
{
	poff
	ssft_display_message "$(gettext "GPRS")" "$(gettext "GPRS disconnected.")"
	exit 0
}

trap disconnect 1 2 3 15

PROVIDERS=(
"default: $(gettext "(No Change)")" \
"o: O2 (Standard GPRS)" \
"p: O2 (Internet-Pack-S/M/L)" \
"e: E-Plus" \
"v: Vodafone" \
"t: T-Mobile" \
"other: (INIT-String)"
)

# MAIN
if [ ! -e /dev/modem ]; then

	ssft_yesno \
		"$(gettext "No modem device selected")" \
		"$(gettext "You have not configured a device for modem / cellphone access yet. Would you like to do this now?")" \
		|| bailout
	/usr/sbin/modemlink
	[ -e /dev/modem ] || bailout
fi

SSFT_DEFAULT="${PROVIDERS[0]}"
ssft_select_single "$(gettext "GPRS - Provider")" "$(gettext "Please select your cellphone provider:")" "${PROVIDERS[@]}"  || bailout 1
[ -n "$SSFT_RESULT" ] && PROVIDER=$(echo $SSFT_RESULT | cut -d: -f1)
unset SSFT_DEFAULT

case "$PROVIDER" in
	default)
		;;
	o)
		INIT='AT+CGDCONT=1,"IP","internet"'
		;;
	p)
		INIT='AT+CGDCONT=1,"IP","surfo2"'
		;;
	e)
		INIT='AT+CGDCONT=1,"IP","internet.eplus.de"'
		;;
	v)
		INIT='AT+CGDCONT=1,"IP","web.vodafone.de"'
		;;
	t)
		INIT='AT+CGDCONT=1,"IP","internet.t-d1.de"'
		;;
	*)
		SSFT_DEFAULT="AT+CGDCONT=1,\"IP\",\"internet\""
		ssft_read_string \
			"$(gettext "GPRS - Provider-String")" \
			"$(gettext "Please enter the INIT string for GPRS that your provider recommends (check your documentation):")"  \
			|| bailout 1
		unset SSFT_DEFAULT
		INIT=$SSFT_RESULT
esac

[ "$PROVIDER" = "default" -o -z "$INIT" ] || perl -pi -e 's/^.*CGDCONT=.*$/OK		'"$INIT"'/g' /etc/chatscripts/gprs

ssft_yesno \
	"$(gettext "GPRS")" \
	"$(gettext "Please be aware that surfing the net over GPRS, while not being onlinetime-dependent, can cause high costs for traffic volume, depending on your provider (usually about 1 cent/kB). You can get a detailled statistic about internet traffic in the \"Root-Shell\" using the program iptraf (on ppp0). Start GPRS Internet Access now?")" \
	|| bailout

[ -x /etc/init.d/sysklogd ] && /etc/init.d/sysklogd start >/dev/null 2>&1
# echo "AT" >/dev/modem
sleep 1

if [ -n "$DISPLAY" ] && [ -x /usr/bin/x-terminal-emulator ]; then
	pon gprs
	x-terminal-emulator -T "$(gettext "GPRS dialup initiated, hit Ctrl-C to disconnect.")" -e bash -c 'tail -n 0 -f /var/log/messages | egrep -e "(chat|ppp)"'
	disconnect
else
	# Start pppd right here.
	/usr/sbin/pppd updetach call gprs 
	sleep 2
	
	exit 0
fi

